[options]
library = "Atspi"
version = "2.0"
work_mode = "normal"
girs_directories = ["./gir-files"]
target_path = "."
generate_safety_asserts = false
deprecate_by_min_version = true
single_version_file = true
generate_display_trait = true
trust_return_value_nullability = false
generate = [
"Atspi.Action",
"Atspi.Application",
"Atspi.Cache",
"Atspi.CollectionMatchType",
"Atspi.CollectionSortOrder",
"Atspi.CollectionTreeTraversalType",
"Atspi.ComponentLayer",
"Atspi.ControllerEventMask",
"Atspi.CoordType",
    "Atspi.DeviceEvent",
    "Atspi.DeviceEventMask",
    "Atspi.DeviceListener",
    "Atspi.DeviceListenerCB",
 "Atspi.DeviceListenerMode",
    "Atspi.DeviceListenerSimpleCB",
"Atspi.Document",
"Atspi.Event",
"Atspi.EventType",
"Atspi.EditableText",
    "Atspi.EventListener",
    "Atspi.EventListenerCB",
# "Atspi.EventListenerMode",
    "Atspi.EventListenerSimpleCB",
"Atspi.Hypertext",
"Atspi.Image",
    "Atspi.KeyDefinition",
    "Atspi.KeyEventMask",
    "Atspi.KeyListenerSyncType",
    "Atspi.KeyMaskType",
# "Atspi.KeySet",
    "Atspi.KeystrokeListener",
    "Atspi.KeySynthType",
    "Atspi.MatchRule",
    "Atspi.Object",
"Atspi.Point",
"Atspi.Range",
"Atspi.Rect",
    "Atspi.Relation",
    "Atspi.RelationType",
"Atspi.Role",
"Atspi.ScrollType",
"Atspi.StateSet",
"Atspi.StateType",
"Atspi.TableCell",
"Atspi.TextBoundaryType",
"Atspi.TextClipType",
"Atspi.TextGranularity",
"Atspi.TextRange",
"Atspi.Value",
]
manual = [
"GLib.Error",
"GLib.Array",
]

[[object]]
name = "Atspi.*"
status = "generate"
    [[object.function]]
    name = "init"
    manual = true
    [[object.function]]
    name = "register_keystroke_listener"
    manual = true

[[object]]
name = "Atspi.Accessible"
status = "generate"
    [[object.function]]
    name = "get_process_id"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "Atspi.Collection"
status = "generate"
    [[object.function]]
    name = "is_ancestor_of"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "Atspi.Component"
status = "generate"
    [[object.function]]
    name = "contains"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "Atspi.Hyperlink"
status = "generate"
    [[object.function]]
    name = "is_valid"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "Atspi.Selection"
status = "generate"
    [[object.function]]
    name = "is_child_selected"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "Atspi.Table"
status = "generate"
    [[object.function]]
    name = "is_column_selected"
        [object.function.return]
        use_return_for_result = true
    [[object.function]]
    name = "is_row_selected"
        [object.function.return]
        use_return_for_result = true
    [[object.function]]
    name = "is_selected"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "Atspi.Text"
status = "generate"
    [[object.function]]
    name = "get_character_at_offset"
    manual = true
