[options]
library = "Atspi"
version = "2.0"
work_mode = "normal"
girs_directories = ["./gir-files"]
target_path = "."
generate_safety_asserts = false
deprecate_by_min_version = true
single_version_file = true
generate_display_trait = true
trust_return_value_nullability = false
generate = [
"Atspi.Accessible",
"Atspi.Action",
"Atspi.Collection",
"Atspi.Component",
"Atspi.Document",
"Atspi.EditableText",
"Atspi.Hypertext",
"Atspi.Image",
"Atspi.Selection",
"Atspi.Table",
"Atspi.TableCell",
"Atspi.Text",
"Atspi.Value",
"Atspi.Hyperlink",
"Atspi.Role",
]
manual = [
"GLib.Error",
]
