[options]
library = "Atspi"
version = "2.0"
work_mode = "normal"
girs_directories = ["./gir-files"]
target_path = "."
generate_safety_asserts = false
deprecate_by_min_version = true
single_version_file = true
generate_display_trait = true
trust_return_value_nullability = false
generate = [
"Atspi.Action",
"Atspi.Collection",
"Atspi.Component",
"Atspi.Document",
"Atspi.EditableText",
"Atspi.Hypertext",
"Atspi.Image",
"Atspi.Selection",
"Atspi.Table",
"Atspi.TableCell",
"Atspi.Text",
"Atspi.Value",
"Atspi.Hyperlink",
"Atspi.Role",
"Atspi.StateSet",
"Atspi.StateType",
"Atspi.Cache",
"Atspi.CoordType",
"Atspi.TextClipType",
"Atspi.Rect",
"Atspi.Range",
"Atspi.TextGranularity",
"Atspi.TextRange",
"Atspi.TextBoundaryType",
"Atspi.ScrollType",
"Atspi.Point",
"Atspi.MatchRule",
"Atspi.ComponentLayer",
"Atspi.CollectionSortOrder",
"Atspi.CollectionTreeTraversalType",
"Atspi.CollectionMatchType",
]
manual = [
"GLib.Error",
"GLib.Array",
]

[[object]]
name = "Atspi.*"
status = "generate"
    [[object.function]]
    name = "init"
    manual = true

[[object]]
name = "Atspi.Accessible"
status = "generate"
    [[object.function]]
        name = "get_process_id"
        [object.function.return]
    use_return_for_result = true
