[options]
library = "Atspi"
version = "2.0"
work_mode = "normal"
girs_directories = ["./gir-files"]
target_path = "."
generate_safety_asserts = false
deprecate_by_min_version = true
single_version_file = true
generate_display_trait = true
trust_return_value_nullability = false
generate = [
"Atspi.Action",
"Atspi.Document",
"Atspi.EditableText",
"Atspi.Hypertext",
"Atspi.Image",
"Atspi.TableCell",
"Atspi.Value",
"Atspi.Role",
"Atspi.StateSet",
"Atspi.StateType",
"Atspi.Cache",
"Atspi.CoordType",
"Atspi.TextClipType",
"Atspi.Rect",
"Atspi.Range",
"Atspi.TextGranularity",
"Atspi.TextRange",
"Atspi.TextBoundaryType",
"Atspi.ScrollType",
"Atspi.Point",
"Atspi.MatchRule",
"Atspi.ComponentLayer",
"Atspi.CollectionSortOrder",
"Atspi.CollectionTreeTraversalType",
"Atspi.CollectionMatchType",
]
manual = [
"GLib.Error",
"GLib.Array",
]

[[object]]
name = "Atspi.*"
status = "generate"
    [[object.function]]
    name = "init"
    manual = true

[[object]]
name = "Atspi.Accessible"
status = "generate"
    [[object.function]]
    name = "get_process_id"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "Atspi.Collection"
status = "generate"
    [[object.function]]
    name = "is_ancestor_of"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "Atspi.Component"
status = "generate"
    [[object.function]]
    name = "contains"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "Atspi.Hyperlink"
status = "generate"
    [[object.function]]
    name = "is_valid"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "Atspi.Selection"
status = "generate"
    [[object.function]]
    name = "is_child_selected"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "Atspi.Table"
status = "generate"
    [[object.function]]
    name = "is_column_selected"
        [object.function.return]
        use_return_for_result = true
    [[object.function]]
    name = "is_row_selected"
        [object.function.return]
        use_return_for_result = true
    [[object.function]]
    name = "is_selected"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "Atspi.Text"
status = "generate"
    [[object.function]]
    name = "get_character_at_offset"
    manual = true
